# Generated by Django 5.1.4 on 2025-06-07 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_app', '0008_alter_patients_photo_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('type_consultation', models.CharField(max_length=20)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.professionals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.patients')),
            ],
            options={
                'verbose_name': 'Consultations',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultations',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.professionals')),
            ],
            options={
                'verbose_name': 'DoctorAvailability',
                'verbose_name_plural': 'DoctorAvailabilities',
                'db_table': 'doctor_availability',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReviewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.professionals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.patients')),
            ],
            options={
                'verbose_name': 'ReviewsUser',
                'verbose_name_plural': 'ReviewsUsers',
                'db_table': 'reviews_user',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
