# Generated by Django 5.0.7 on 2024-12-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resume', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('images', models.ImageField(blank=True, upload_to='tips/')),
                ('alt_image', models.CharField(max_length=200)),
            ],
        ),
    ]
