# Generated by Django 5.0.7 on 2024-12-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contenttips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttips',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'ContentTips', 'verbose_name_plural': 'ContentTips'},
        ),
        migrations.AlterModelOptions(
            name='faqbank',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'FaqBank', 'verbose_name_plural': 'FaqBanks'},
        ),
        migrations.AlterModelTable(
            name='contenttips',
            table='content_tips',
        ),
        migrations.AlterModelTable(
            name='faqbank',
            table='faq_bank',
        ),
    ]
