# Generated by Django 5.1 on 2024-11-06 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fone", models.CharField(max_length=15)),
                ("senha", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Pacientes",
            fields=[
                (
                    "usuarios_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cadastro_app.usuarios",
                    ),
                ),
            ],
            bases=("cadastro_app.usuarios",),
        ),
        migrations.CreateModel(
            name="Profissionais",
            fields=[
                (
                    "usuarios_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cadastro_app.usuarios",
                    ),
                ),
                ("registro", models.CharField(max_length=80)),
            ],
            bases=("cadastro_app.usuarios",),
        ),
    ]
