# Generated by Django 5.0.7 on 2024-11-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='profissionais',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profissionais',
            old_name='senha',
            new_name='password',
        ),
    ]
