# Generated by Django 5.0.7 on 2024-11-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0002_rename_nome_pacientes_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissionais',
            old_name='registro',
            new_name='register',
        ),
        migrations.AddField(
            model_name='profissionais',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
