# Generated by Django 5.0.7 on 2024-11-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0003_rename_registro_profissionais_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='photo_perfil',
            field=models.ImageField(null=True, upload_to='photo_profile/'),
        ),
        migrations.AddField(
            model_name='profissionais',
            name='photo_perfil',
            field=models.ImageField(null=True, upload_to='photo_profile/'),
        ),
    ]
