# Generated by Django 5.0.7 on 2024-12-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_user_app', '0001_initial'),
        ('register_app', '0006_alter_patients_photo_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.patients'),
        ),
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('type_consultation', models.CharField(max_length=20)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.professionals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.patients')),
            ],
            options={
                'verbose_name': 'Consultations',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultations',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
