# Generated by Django 5.0.7 on 2025-01-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_user_app', '0003_rename_id_specialist_reviewsuser_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
