# Generated by Django 5.1.4 on 2025-06-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area_user_app', '0004_consultations_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsuser',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='reviewsuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Consultations',
        ),
        migrations.DeleteModel(
            name='ReviewsUser',
        ),
    ]
