# Generated by Django 5.0.7 on 2024-12-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0002_patients_professionals_delete_pacientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='professionals',
            name='auth_user',
        ),
    ]
