# Generated by Django 5.0.7 on 2024-12-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0004_remove_patients_email_remove_patients_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Patients', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='professionals',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Professionals', 'verbose_name_plural': 'Professionals'},
        ),
        migrations.AlterModelTable(
            name='patients',
            table='patients',
        ),
        migrations.AlterModelTable(
            name='professionals',
            table='professionals',
        ),
    ]
