# Generated by Django 5.0.7 on 2024-12-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0005_alter_patients_options_alter_professionals_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='photo_perfil',
            field=models.ImageField(null=True, upload_to='photo_profile/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='photo_perfil',
            field=models.ImageField(null=True, upload_to='photo_profile/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='specialty',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
    ]
