# Generated by Django 5.0.7 on 2024-12-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0007_alter_professionals_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='photo_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='photo_profile/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='photo_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='photo_profile/<django.db.models.fields.CharField>'),
        ),
    ]
