# Generated by Django 5.0.7 on 2024-11-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0002_contenttips'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttips',
            name='alt_image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
